kind: pipeline
name: default
type: docker

steps:
  - name: build & push gitea
    image: docker:dind
    volumes:
      - name: dockersock
        path: /var/run
    environment:
      DOCKER_GITEA_PASSWORD:
        from_secret: DOCKER_GITEA_PASSWORD
      DOCKER_GITEA_USERNAME:
        from_secret: DOCKER_GITEA_USERNAME
      DOCKER_GITEA_HOST:
        from_secret: DOCKER_GITEA_HOST
    commands:
      - sleep 5 # give docker enough time to start
      - echo $DOCKER_GITEA_PASSWORD | docker login --username $DOCKER_GITEA_USERNAME --password-stdin $DOCKER_GITEA_HOST
      - DOCKER_BUILDKIT=1 docker build --no-cache -t $DOCKER_GITEA_HOST/$DOCKER_GITEA_USERNAME/qbittorrentvpn:latest -t $DOCKER_GITEA_HOST/$DOCKER_GITEA_USERNAME/qbittorrentvpn:$(date '+%Y-%m-%d') .
      - docker push --all-tags $DOCKER_GITEA_HOST/$DOCKER_GITEA_USERNAME/qbittorrentvpn

services:
  - name: docker
    image: docker:dind
    privileged: true
    volumes:
      - name: dockersock
        path: /var/run

volumes:
  - name: dockersock
    temp: {}

trigger:
  branch:
    - main
  event:
    - push